src/WebPoll.Web/Models/Accounts/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebPoll.Web.Models.Accounts
{
    public class LoginViewModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

src/WebPoll.Web/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebPoll.Web.Models.Accounts;

namespace WebPoll.Web.Controllers
{
    public class AccountController : Controller
    {
        //
        // GET: /Account/

        public ActionResult Login(LoginViewModel login)
        {
            return Json(true);
        }

    }
}

src/WebPoll.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebPoll.Web.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

src/WebPoll.Web/Controllers/PollController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebPoll.Web.Controllers
{
    public class PollController : Controller
    {
        //
        // GET: /Poll/

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Index(int? id)
        {
            if (!id.HasValue)
            {
                return View();
            }
            if (id.Value == 3)
            {
                return View("Results");
            }
            return View("IncompletePoll");
        }

        public ActionResult Vote(Guid id)
        {
            return View();
        }

    }
}

src/WebPoll.Web/Views/Home/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section AboveContainer
{
    <div class="jumbotron">
        <div class="container">
            <h1>Web Poll</h1>
            <p>Create your own simple, secure and transparent online poll in minutes! Just click the button below to get started</p>
            <p><a class="btn btn-primary btn-lg" href="@Url.Action("Create","Poll")" role="button">Create your own poll &raquo;</a></p>
        </div>
    </div>
}

    <div class="row">
        <div class="col-md-4">
            <h2>Democratic</h2>
            <p>Web Poll was created to showcase the ideal form of group decision making. We're hoping that you will be able to see the benefits to our polling system and demand a similar system for your government </p>
            <p>
                <a class="btn btn-default" href="#" role="button">Read More &raquo;</a>
            </p>
        </div>
        <div class="col-md-4">
            <h2>Open Source</h2>
            <p>Wondering how it works? Want to help improve it? Well you are in luck because not only is Web Poll free but it's also completely open source, you can verify how it works and that it works and you can set up your own version</p>
            <p><a class="btn btn-default" target="_blank" href="https://github.com/EvaKnievel/WebPoll" role="button">View Source &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Transparent</h2>
            <p>Web Poll makes sure that your poll, we give every voter a unique ID that only they know they have and when the poll is complete they can verify that their vote was counted correctly  </p>
            <p><a class="btn btn-default" href="#" role="button">Read More &raquo;</a></p>
        </div>
    </div>

src/WebPoll.Web/Views/Poll/Create.cshtml
@model dynamic

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section scripts
{
    @Scripts.Render("~/Scripts/vms/CreatePollViewModel.js")
    <script type="text/javascript">
        $(function () {
            $("#pollEndDate").datepicker({ minDate: 0, dateFormat: "yy-mm-dd"});
        });

    </script>
}
<h2>Create a poll</h2>
<form id="CreatePoll">
    <div id="pollSettings">
        <div class="form-group" data-bind="validationElement: pollName">
            <label for="pollName">Poll Name</label>
            <input type="text" class="form-control" data-bind="value: pollName" name="pollName" placeholder="Enter Poll Name">
        </div>
        <div class="form-group">
            <label for="pollOption">Poll Options</label>
            <ul class="formList" data-bind="foreach: pollOptions ">
                <li>
                    <div class="row" data-bind="validationElement: name">
                        <div class="col-xs-11">
                            <input type="text" class="form-control" name="pollOption" data-bind="value:name" placeholder="Enter Option Name">
                        </div>
                        <div class="col-xs-1">
                            <button type="button" class="btn btn-danger" data-bind="click:$root.deleteOption, enable: $root.pollOptions().length > 2 && $root.deleteOption">
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                            </button>
                        </div>
                    </div>
                </li>
            </ul>
            <button class="btn btn-success" data-bind="click: addNewPollOption">Add new poll option</button>
        </div>
        <div class="form-group" data-bind="validationElement: winningOptions">
            <label for="winningOptions">How many winning options can there be?</label>
            <input type="number" class="form-control" data-bind="value: winningOptions" name="winningOptions" placeholder="Enter number of winning options here">
        </div>
        <div class="form-group" data-bind="validationElement: pollEndDate">
            <label for="pollEndDate">When should the last day of the poll be?</label>
            <input type="date" data-bind="value: pollEndDate" class="form-control" id="pollEndDate" name="pollEndDate" placeholder="Enter the date here">
        </div>
    </div>
    <div id="voterSettings">
        <div class="form-group">
            <label for="voterEmail">Voter Details</label>
            <ul class="formList" data-bind="foreach: voters ">
                <li class="row">
                    <div class="col-xs-6" data-bind="validationElement: name"><input type="email" class="form-control" data-bind="value: name" id="voterEmail" placeholder="Enter voter name"></div>
                    <div class="col-xs-5" data-bind="validationElement: email"><input type="email" class="form-control" data-bind="value: email" id="voterEmail" placeholder="Enter voter email"></div>
                    <div class="col-xs-1">
                        <button type="button" class="btn btn-danger" title="Delete Voter" data-bind="click:$root.deleteVoter, enable: $root.voters().length > 2 && $root.deleteOption">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        </button>
                    </div>
                </li>
            </ul>
            <button class="btn btn-success" data-bind="click: addNewVoter">Add new voter</button>

        </div>
        <div class="checkbox">
            <label>
                <input type="checkbox" data-bind="value: includeCreatorAsVoter"> Do you want to be included as a voter?
            </label>
        </div>
        <div class="form-group" data-bind="validationElement: message">
            <label for="message">Optional message to be included in the email sent to voters</label>
            <textarea class="form-control" id="message" data-bind="text: message" placeholder="Enter message here"></textarea>
        </div>
    </div>
    <div>
        <div class="form-group" data-bind="validationElement: yourEmail">
            <label for="yourEmail">Your Email Address</label>
            <input type="email" class="form-control" id="yourEmail" data-bind="value: yourEmail" placeholder="Enter your email">
        </div>
        <div class="form-group" data-bind="validationElement: password">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" data-bind="value: password" placeholder="Enter password">
        </div>
        <div class="form-group" data-bind="validationElement: confirmPassword">
            <label for="confirmPassword">Password Confirmation</label>
            <input type="password" class="form-control" id="confirmPassword" data-bind="value: confirmPassword" placeholder="Confirm your password">
        </div>
    </div>
    <a role="button" href="#" data-bind="click: submit" class="btn btn-default">Submit</a>
</form>

src/WebPoll.Web/Views/Poll/IncompletePoll.cshtml
@model dynamic

@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Which Restaurant do we like</h2>
<p>This Poll isn't finished yet, here are the people who still have to vote, the poll will expire on the 2nd of January</p>
<table class="table-striped table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Joe Smith</td>
            <td><a href="mailto:joesmith@joe.ie">joesmith@joe.ie</a></td>
        </tr>
        <tr>
            <td>Jane Smith</td>
            <td><a href="mailto:joesmith@joe.ie">janesmith@joe.ie</a></td>
        </tr>
    </tbody>
</table>

<a class="btn btn-primary" href="#" role="button">Send a reminder</a>
<a class="btn btn-warning" href="#" role="button">Finish the poll early</a>

src/WebPoll.Web/Views/Poll/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Your Polls</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <a href="@Url.Action("Index", new { id = 1 })">Which Restaurant do we like?</a>
            </td>
            <td>
                In Progress
            </td>
            <td>
                Delete
            </td>
        </tr>
        <tr>
            <td>
                <a href="@Url.Action("Index",new {id = 2})">What 3 things do we want to do on Friday</a>
            </td>
            <td>
                In Progress
            </td>
            <td>
                Delete
            </td>
        </tr>
        <tr class="success">
            <td>
                <a href="@Url.Action("Index",new {id = 3})">Dublin South–East 2011</a>
            </td>
            <td>
                Finished
            </td>
            <td>
                Delete
            </td>
        </tr>
    </tbody>
</table>
<a class="btn btn-primary" href="@Url.Action("Create","Poll")" role="button">Create new Poll</a>

src/WebPoll.Web/Views/Poll/Results.cshtml
@model dynamic

@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dublin South–East 2011 Results</h2>
<h3>Winners</h3>
<table class="table table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th>Candidate</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>1</td>
            <td>Ruairi Quinn</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Lucinda Creighton</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Eoghan Murphy</td>
        </tr>
        <tr>
            <td>4</td>
            <td>Kevin Humphreys</td>
        </tr>
    </tbody>
</table>

<h3>Results Breakdown</h3>
<table class="table table-striped">
    <thead>
        <tr>
            <th colspan="14">2011 general election: Dublin South–East</th>
        </tr>
        <tr>
            <th colspan="2">Party</th>
            <th>Candidate</th>
            <th>&nbsp;% 1st Pref</th>
            <th>Count 1</th>
            <th>Count 2</th>
            <th>Count 3</th>
            <th>Count 4</th>
            <th>Count 5</th>
            <th>Count 6</th>
            <th>Count 7</th>
            <th>Count 8</th>
            <th>Count 9</th>
            <th>Count 10</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th></th>
            <td>Labour Party</td>
            <td>Ruairi Quinn</td>
            <td>15.5</td>
            <td>5,407</td>
            <td>5,562</td>
            <td>5,800</td>
            <td>6,147</td>
            <td>6,600</td>
            <td>7,555</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <th></th>
            <td>Fine Gael</td>
            <td>Lucinda Creighton</td>
            <td>19.0</td>
            <td>6,619</td>
            <td>6,694</td>
            <td>6,801</td>
            <td>6,855</td>
            <td>6,969</td>
            <td>7,428</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <th></th>
            <td>Fine Gael</td>
            <td>Eoghan Murphy</td>
            <td>16.6</td>
            <td>5,783</td>
            <td>5,843</td>
            <td>5,891</td>
            <td>5,938</td>
            <td>6,136</td>
            <td>6,534</td>
            <td>6,636</td>
            <td>6,915</td>
            <td>8,356</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <th></th>
            <td>Labour Party</td>
            <td>Kevin Humphreys</td>
            <td>9.9</td>
            <td>3,450</td>
            <td>3,568</td>
            <td>3,764</td>
            <td>4,059</td>
            <td>4,294</td>
            <td>4,674</td>
            <td>5,019</td>
            <td>5,057</td>
            <td>5,894</td>
            <td>6,421</td>
        </tr>
        <tr>
            <th></th>
            <td>Fianna Fáil</td>
            <td>Chris Andrews</td>
            <td>11.2</td>
            <td>3,922</td>
            <td>3,981</td>
            <td>4,059</td>
            <td>4,160</td>
            <td>4,248</td>
            <td>4,498</td>
            <td>4,545</td>
            <td>4,594</td>
            <td>4,950</td>
            <td>5,193</td>
        </tr>
        <tr>
            <th></th>
            <td>Independent</td>
            <td>Paul Sommerville</td>
            <td>6.7</td>
            <td>2,343</td>
            <td>2,492</td>
            <td>2,621</td>
            <td>2,815</td>
            <td>3,196</td>
            <td>3,457</td>
            <td>3,534</td>
            <td>3,566</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <th></th>
            <td>Green Party</td>
            <td>John Gormley</td>
            <td>6.8</td>
            <td>2,370</td>
            <td>2,435</td>
            <td>2,547</td>
            <td>2,659</td>
            <td>2,908</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <th></th>
            <td>Independent</td>
            <td>Dylan Haskins</td>
            <td>4.0</td>
            <td>1,383</td>
            <td>1,492</td>
            <td>1,754</td>
            <td>1,928</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <th></th>
            <td>Sinn Féin</td>
            <td>Ruadhán Mac Aodháin</td>
            <td>3.6</td>
            <td>1,272</td>
            <td>1,405</td>
            <td>1,549</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <th></th>
            <td>Independent</td>
            <td>Gerard Mannix Flynn</td>
            <td>3.6</td>
            <td>1,248</td>
            <td>1,403</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <th></th>
            <td>People Before Profit</td>
            <td>Annette Mooney</td>
            <td>1.8</td>
            <td>626</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <th></th>
            <td>Independent</td>
            <td>Hugh Sheehy</td>
            <td>0.6</td>
            <td>195</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <th></th>
            <td>Independent</td>
            <td>James Coyle</td>
            <td>0.5</td>
            <td>164</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <th></th>
            <td>Independent</td>
            <td>Noel Watson</td>
            <td>0.3</td>
            <td>89</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <th></th>
            <td>Independent</td>
            <td>John Keigher</td>
            <td>0.1</td>
            <td>27</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <th></th>
            <td>Fís Nua</td>
            <td>Peadar Ó Ceallaigh</td>
            <td>0.1</td>
            <td>18</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td colspan="14">Electorate: 58,217 &nbsp; Valid: 34,919 &nbsp; Spoilt: 327 (0.9%) &nbsp; Quota: 6,984 &nbsp; Turnout: 35,246 (60.5%)</td>
        </tr>
    </tbody>
</table>
<a class="btn btn-primary" href="#">Download Vote Data</a>
<p> Vote data can be used to perform an independent count to verify the results</p>

src/WebPoll.Web/Views/Poll/Vote.cshtml
@model dynamic

@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section scripts
{
    @Scripts.Render("~/Scripts/vms/VoteViewModel.js")
}
<h2>Which Restaurant do we like</h2>
<p>Drag each of the options below into the order that you prefer, would the option you most prefer at the top, 2nd preference directly below and so on till the option you least prefer</p>
<ul class="list-group" data-bind="sortable: pollOptions">
    <li class="list-group-item" data-bind="text: name"></li>
</ul>
<button class="btn btn-primary" data-bind="click: submit">Vote</button>

src/WebPoll.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewBag.Title Web Poll</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Eva Lacy">
    <!-- Style Sheet Section -->
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/bootstrap")
        @Styles.Render("~/Content/themes/base/css")
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Home")">Web Poll</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <form class="navbar-form navbar-right">
                    <div class="form-group">
                        <input type="text" placeholder="Email" class="form-control">
                    </div>
                    <div class="form-group">
                        <input type="password" placeholder="Password" class="form-control">
                    </div>
                    <button type="submit" class="btn btn-success">Sign in</button>
                </form>
            </div>
        </div>
    </nav>
    @RenderSection("AboveContainer",false)
    <div class="container">
        @RenderBody()

        <hr>

        <footer>
            <p>This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/moment")
    @Scripts.Render("~/bundles/knockout")
    @Scripts.Render("~/bundles/knockout-validation")
    @Scripts.Render("~/bundles/knockout-sortable")
    @Scripts.Render("~/bundles/site")
    @Scripts.Render("~/bundles/knockoutViewModels")
    @RenderSection("scripts", required: false)
</body>
</html>